/**
 * "It imported cleanly - remember it."
 *
 * A load sheet the app generated for an attribute it did not know is, once it
 * has actually run, exactly the evidence the library is made of: a script that
 * worked against production. Saving it makes the attribute known - it appears
 * in the field picker, the resolver will use it, and it stops being flagged.
 *
 * The user is the one asserting it worked; nothing here can check. So it is
 * only ever saved on their say-so, and the record says where it came from.
 */

import type { Db } from '../db/index.js';
import type { HeaderBlock, LibraryTemplate } from '../../shared/library.js';
import { slugForFiles } from '../domain/generate.js';
import { getTemplate, loadLibrary, saveTemplate } from './libraryService.js';
import { generateFromRequest, type SheetRequest } from './sheetService.js';

export interface LearnResult {
  template: { id: string; name: string };
  /** Attributes that were unverified and are now in the library. */
  learned: string[];
}

function blockFromGenerated(block: Awaited<ReturnType<typeof generateFromRequest>>['resolved']['blocks'][number]): HeaderBlock {
  return {
    op: block.op,
    itemType: block.itemType,
    columns: block.columns.map((column) => column.column),
    ...(block.csv
      ? {
          csv: {
            file: block.csv.file,
            encoding: block.csv.encoding,
            delimiter: block.csv.delimiter,
            linesToSkip: block.csv.linesToSkip,
            columnsOffset: block.csv.columnsOffset,
          },
          layout: block.csv.layout,
          csvHeaderRow: block.csv.headerRow,
          csvLabels: block.columns.map((column) => column.label),
        }
      : {}),
  };
}

/** A record added twice under the same name gets its own id rather than overwriting the first. */
async function freeId(db: Db, base: string): Promise<string> {
  if (!(await getTemplate(db, base))) return base;
  for (let suffix = 2; suffix < 100; suffix++) {
    const candidate = `${base}-${suffix}`;
    if (!(await getTemplate(db, candidate))) return candidate;
  }
  return `${base}-${Date.now()}`;
}

export async function learnFromSheet(db: Db, request: SheetRequest, confirmedBy?: string): Promise<LearnResult> {
  const sheet = await generateFromRequest(db, request);
  const before = (await loadLibrary(db)).catalogue;
  const unverified = sheet.resolved.blocks
    .flatMap((block) => block.columns)
    .filter((column) => column.status === 'unverified')
    .map((column) => column.column.name);

  const now = new Date().toISOString();
  const slug = slugForFiles(request.name);
  const id = await freeId(db, `user-${slug.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()}`);

  const template: LibraryTemplate = {
    id,
    name: `Added in app / ${request.name}`,
    sourcePath: `added-in-app/${slug}.impex`,
    group: 'Added in app',
    direction: sheet.resolved.direction,
    dataSource: sheet.csvs.length > 0 ? 'externalCsv' : 'inline',
    blocks: sheet.resolved.blocks.map(blockFromGenerated),
    macros: Object.fromEntries(sheet.resolved.macros),
    origin: 'user',
    // The user has said it imported cleanly, which is the only verification
    // available without a live SAP connection.
    verified: true,
    notes: `Generated by this app and confirmed as imported cleanly on ${now.slice(0, 10)}${
      confirmedBy ? ` by ${confirmedBy}` : ''
    }.`,
    createdAt: now,
    updatedAt: now,
  };

  await saveTemplate(db, template);

  const after = (await loadLibrary(db)).catalogue;
  const learned = unverified.filter(
    (attribute) =>
      after.find(request.itemType, attribute) !== undefined && before.find(request.itemType, attribute) === undefined,
  );

  return { template: { id: template.id, name: template.name }, learned };
}
