/**
 * Writing the .impex script and its CSV.
 *
 * Both input modes end up here and nowhere else: the field picker and the
 * natural-language resolver each produce a specification, and this is the only
 * code that turns one into files. Nothing upstream writes ImpEx text.
 */

import { writeCsv } from '../../shared/csv.js';
import { normaliseBoolean } from '../../shared/fieldTypes.js';
import type { LoadSheetSpec } from '../../shared/spec.js';
import { resolveSpec, type ResolvedBlock, type ResolvedLoadSheet, type ResolveContext } from './resolve.js';
import { hasErrors, validate, type Finding, type GeneratedFile } from './validate.js';

export interface GeneratedLoadSheet {
  name: string;
  resolved: ResolvedLoadSheet;
  impex: GeneratedFile;
  csvs: GeneratedFile[];
  findings: Finding[];
  /** Plain English, for the check-before-you-download panel (§6.1). */
  summary: string;
  /** False when a finding would make the import fail; the packager refuses on this. */
  packageable: boolean;
}

/** `Editors Pick` -> `EditorsPick`, for file names. */
export function slugForFiles(name: string): string {
  const cleaned = name
    .replace(/[^A-Za-z0-9 ]+/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
    .map((word) => (/^[A-Z0-9]+$/.test(word) ? word : word.charAt(0).toUpperCase() + word.slice(1)))
    .join('');
  return cleaned || 'LoadSheet';
}

const PREAMBLE_CODE_EXECUTION = '"#% impex.enableCodeExecution(true);"';

/** Written exactly as WOSG writes it, spacing included - these files get diffed against old ones. */
export function includeCall(csv: {
  file: string;
  encoding: string;
  delimiter: string;
  linesToSkip: number;
  columnsOffset: number;
}): string {
  return `"#% impex.includeExternalDataMedia( ""${csv.file}"", ""${csv.encoding}"", '${csv.delimiter}', ${csv.linesToSkip}, ${csv.columnsOffset});"`;
}

export function headerLine(block: ResolvedBlock): string {
  return `${block.op} ${block.itemType};${block.columns.map((c) => c.expression).join(';')}`;
}

function wrapComment(text: string, width = 76): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = '';
  for (const word of words) {
    if (line.length > 0 && line.length + 1 + word.length > width) {
      lines.push(line);
      line = word;
    } else {
      line = line.length === 0 ? word : `${line} ${word}`;
    }
  }
  if (line) lines.push(line);
  return lines.map((l) => `# ${l}`);
}

function writeImpex(resolved: ResolvedLoadSheet, generatedAt: string, templateName?: string): string {
  const lines: string[] = [`# ${resolved.name}`];
  if (resolved.intent) lines.push(...wrapComment(resolved.intent));
  lines.push('#', `# Generated by the WOSG Load Sheet Generator on ${generatedAt}.`);
  if (templateName) {
    lines.push(...wrapComment(`Conventions, including columnsOffset, copied from the library template: ${templateName}.`));
  }

  // The unverified columns are called out at the top as well as beside their
  // block, because this is the comment somebody reads before they upload.
  const unverified = resolved.blocks.flatMap((b) => b.columns.filter((c) => c.status === 'unverified'));
  if (unverified.length > 0) {
    lines.push('#');
    lines.push(
      ...wrapComment(
        `UNVERIFIED: ${unverified.map((c) => c.column.name).join(', ')} ` +
          `${unverified.length === 1 ? 'is' : 'are'} not in the load sheet library. ` +
          `This script was generated anyway - check the attribute ` +
          `${unverified.length === 1 ? 'name exists' : 'names exist'} on the item type in SAP Commerce before importing.`,
      ),
    );
  }

  lines.push('');
  lines.push(PREAMBLE_CODE_EXECUTION);
  for (const [name, definition] of resolved.macros) lines.push(`$${name}=${definition}`);

  for (const block of resolved.blocks) {
    lines.push('');
    for (const column of block.columns) {
      if (column.status !== 'unverified') continue;
      const suggestion = column.suggestions?.length
        ? ` Closest known ${column.suggestions.length === 1 ? 'attribute' : 'attributes'}: ${column.suggestions.join(', ')}.`
        : '';
      lines.push(...wrapComment(`UNVERIFIED COLUMN: ${column.expression} - not in the load sheet library.${suggestion}`));
    }
    lines.push(headerLine(block));
    if (block.csv) lines.push(includeCall(block.csv));
  }

  lines.push('');
  return lines.join('\n');
}

function writeBlockCsv(block: ResolvedBlock): GeneratedFile | undefined {
  if (!block.csv) return undefined;
  const prefix = block.csv.layout.typeColumn ? [''] : [];
  const rows = block.rows.map((row) => [
    ...prefix,
    ...block.columns.map((column, index) => {
      const value = row[index] ?? '';
      // Booleans are written in capitals whatever the user typed; a value that
      // is not a boolean at all is left alone for the validator to report.
      if (column.shape.type !== 'boolean') return value;
      return normaliseBoolean(value) ?? value;
    }),
  ]);
  return {
    filename: block.csv.file,
    content: writeCsv([block.csv.headerRow, ...rows], block.csv.delimiter),
  };
}

function summarise(resolved: ResolvedLoadSheet, findings: Finding[]): string {
  const parts: string[] = [];
  for (const block of resolved.blocks) {
    const key = block.columns.filter((c) => c.unique).map((c) => c.column.name);
    const fields = block.columns.filter((c) => !c.unique && c.column.kind === 'attribute');
    const rows = block.rows.length;
    parts.push(
      `${block.op} on ${block.itemType}${key.length ? ` keyed on ${key.join(' + ')}` : ''}, ` +
        `${fields.length} field${fields.length === 1 ? '' : 's'}` +
        (block.csv
          ? `, read from ${block.csv.file} (${rows === 0 ? 'empty template, headings only' : `${rows} row${rows === 1 ? '' : 's'}`}, columnsOffset ${block.csv.columnsOffset})`
          : ', written inline'),
    );
  }
  const errors = findings.filter((f) => f.severity === 'error').length;
  const warnings = findings.filter((f) => f.severity === 'warning').length;
  if (errors > 0) parts.push(`${errors} problem${errors === 1 ? '' : 's'} must be fixed before this can be packaged.`);
  else if (warnings > 0) parts.push(`${warnings} thing${warnings === 1 ? '' : 's'} to check before importing.`);
  else parts.push('No problems found.');
  return parts.join('. ').replace(/\.\./g, '.');
}

export function generateLoadSheet(
  spec: LoadSheetSpec,
  context: ResolveContext,
  options: { generatedAt?: string } = {},
): GeneratedLoadSheet {
  const resolved = resolveSpec(spec, context);
  const generatedAt = options.generatedAt ?? new Date().toISOString().slice(0, 10);
  const templateName = context.templates.find((t) => t.id === spec.basedOnTemplateId)?.name;

  const impex: GeneratedFile = {
    filename: `${slugForFiles(spec.name)}.impex`,
    content: writeImpex(resolved, generatedAt, templateName),
  };
  const csvs = resolved.blocks.map(writeBlockCsv).filter((f): f is GeneratedFile => f !== undefined);
  const findings = validate({ resolved, impex, csvs });

  return {
    name: spec.name,
    resolved,
    impex,
    csvs,
    findings,
    summary: summarise(resolved, findings),
    packageable: !hasErrors(findings),
  };
}
